### ISSUE TITLE
bundle exec rake tests fail on 2.2.0

### ISSUE THREAD

**Issue by tbunnyman** [knife-block/knife-block#29]
Travis error below. This looks like the test framework used is changed and possibly moved from default in 2.2.0
https://www.ruby-lang.org/en/news/2014/12/25/ruby-2-2-0-released/

```
home/travis/build/knife-block/knife-block/test/unit/knifeblock_test.rb:7:in `require': cannot load such file -- test/unit (LoadError)
	from /home/travis/build/knife-block/knife-block/test/unit/knifeblock_test.rb:7:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `require'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `each'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:9:in `block in <main>'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib"  "/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/unit/*_test.rb" ]
/home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by solarce** [comment]
Thanks, I expect to merge this soon
