### ISSUE TITLE
knife block does not exist

### ISSUE THREAD

**Issue by spuder** [knife-block/knife-block#32]
Using the chefdk on mac os x using rvm, I find that when I do `gem install knife-block` that the executable is not in my path. 

```bash
sowens-MBP:Devops sowen$ gem install knife-block
Successfully installed knife-block-0.1.1
Parsing documentation for knife-block-0.1.1
Done installing documentation for knife-block after 0 seconds
1 gem installed
sowens-MBP:Devops sowen$ knife block user list
FATAL: Cannot find sub command for: 'block user list'
```

I'm pretty new to chef, but I'm guessing this has something to do with the install location of the chefdk? 

```bash
sowens-MBP:Devops sowen$ which knife
/opt/chefdk/bin/knife
```

Does this gem work with the most recent versions of chef?

**Comment by tbunnyman** [comment]
use `chef gem install knife-block`
You will want to do this for all knife add ons

**Comment by spuder** [comment]
That worked, thanks. I had to use `sudo`. I'll open a pull request.

**Comment by spuder** [comment]
Actually that didn't work.

```bash
sowens-MBP:Devops sowen$ sudo knife block list -VV
INFO: Using configuration from /Users/sowen/.chef/knife.rb
/Users/sowen/.chefdk/gem/ruby/2.1.0/gems/knife-block-0.1.1/lib/chef/knife/block.rb:16:in `get_config_file': undefined method `locate_config_file' for Chef::Knife:Class (NoMethodError)
	from /Users/sowen/.chefdk/gem/ruby/2.1.0/gems/knife-block-0.1.1/lib/chef/knife/block.rb:38:in `chef_config_base'
	from /Users/sowen/.chefdk/gem/ruby/2.1.0/gems/knife-block-0.1.1/lib/chef/knife/block.rb:75:in `check_block_setup'
	from /Users/sowen/.chefdk/gem/ruby/2.1.0/gems/knife-block-0.1.1/lib/chef/knife/block.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:40:in `load'
	from /opt/chefdk/bin/knife:40:in `<main>'
```

I don't know why it is looking for ruby 2.1.0 since I'm using ruby 2.2

```
rvm list
Warning! PATH is not properly set up, '/Users/sowen/.rvm/gems/ruby-2.2.0/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.0'.

rvm rubies

   ruby-2.0.0-p598 [ x86_64 ]
=* ruby-2.2.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

Perhaps this gem doesn't work with rvm or because I installed with sudo 

```
sowens-MBP:Devops sowen$ chef gem install knife-block
Fetching: knife-block-0.1.1.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/sowen/.chefdk/gem/ruby/2.1.0/cache/knife-block-0.1.1.gem
```

**Comment by spuder** [comment]
I tried uninstalling and reinstalling this gem, making sure that the chefdk was at the front of my path. 

```
sowens-MBP:.chef sowen$ chef gem install knife-block
Fetching: knife-block-0.1.1.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/sowen/.chefdk/gem/ruby/2.1.0/cache/knife-block-0.1.1.gem
sowens-MBP:.chef sowen$ sudo !!
sudo chef gem install knife-block
Password:
sowens-MBP:.chef sowen$ which chef
/opt/chefdk/bin/chef
sowens-MBP:.chef sowen$ sudo chef gem install knife-block
Password:
WARNING:  You don't have /Users/sowen/.chefdk/gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed knife-block-0.1.1
1 gem installed

sowens-MBP:.chef sowen$ knife block
ERROR: knife encountered an unexpected error
This may be a bug in the 'block' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `locate_config_file' for Chef::Knife:Class

```

I'm not sure it is possible to install this gem on Mac using the chefdk and RVM.

**Comment by solarce** [comment]
I'm working on getting master working again, I've gotten Travis-CI testing with ChefDK + 2.1](https://github.com/knife-block/knife-block/pull/35), and I'm gonna see if I can get the Travis OSX build support enabled, so I can include OSX + RVM testing.

Please stay tuned!
